project.SistemaNF/CSharks.NFEs.WebApp/Controllers/NfeController.cs
using CSharks.NFEs.Domain.DTOs;
using CSharks.NFEs.Domain.Interfaces.Repositories;
using CSharks.NFEs.Domain.Models;
using CSharks.NFEs.Domain.Models.NF;
using CSharks.NFEs.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CSharks.NFEs.WebApp.Controllers
{
    public class NfeController : Controller
    {
        private readonly IServicesRepository _serviceRepo;
        private readonly IClientRepository _clientRepo;
        private readonly IApiClientService _serviceApi;
        private readonly IEmitedNfRepository _emitedRepo;

        public NfeController(IServicesRepository serviceRepo, IClientRepository clientRepo, IApiClientService serviceApi, IEmitedNfRepository emitedRepo)
        {
            _serviceRepo = serviceRepo;
            _clientRepo = clientRepo;
            _serviceApi = serviceApi;
            _emitedRepo = emitedRepo;
        }
        public IActionResult Index()
        {
            ViewBag.ListEmiteds = _emitedRepo.GetAll().ToList();
            return View();
        }

        public IActionResult DownloadAction(string fileName)
        {
            string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files", $"{fileName}.xml");

            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }

            string fileUrl = Url.Content("~/files/" + $"{fileName}.xml");
            return Json(new { fileUrl = fileUrl });
        }

    }
}

project.SistemaNF/CSharks.NFEs.WebApp/Views/Nfe/EmitNF.cshtml
@using CSharks.NFEs.Domain.Models;
@{
    List<Service> services = ViewBag.services;
    List<Client> clients = ViewBag.clients;
    ViewData["Title"] = "Shark NFE - NFEs";
}

<section>
    <div class="container">
        <div class="form-control">
            <div class="mt-4">
                <h2> Emitir uma nova Nota Fiscal </h2>
            </div>
            <div class="mt-4">
                <label> Identificador </label>
                <input class="form-control" />
            </div>
            <div>
                <label> Serviços </label>
                <select class="form-control">
                    @if (services != null && services.Any())
                    {
                        foreach (Service service in services)
                        {
                            <option value="@service.codigo_item_lista_servico">@service.codigo_item_lista_servico - @service.descritivo</option>
                        }
                    }
                    else
                    {
                        <option> Cadastre um Serviço. </option>
                    }

                </select>
            </div>
            <div>
                <label> Clientes </label>
                <select class="form-control">
                    @if (clients != null && clients.Any())
                    {
                        foreach (Client client in clients)
                        {
                            <option value="#">@client.CpfCnpj</option>
                        }
                    }
                    else
                    {
                        <option> Cadastre um Cliente. </option>
                    }

                </select>
            </div>
            <div> 
                <a class="btn btn-primary mt-4"> Emitir </a>
            </div>
        </div>
        
    </div>
</section>

@section Scripts {
    <script type="text/javascript">

    </script>
}

project.SistemaNF/CSharks.NFEs.WebApp/Views/Nfe/HystoryNF.cshtml
@{
    ViewData["Title"] = "Shark NFE - NFEs";
}

<section>

</section>

@section Scripts {
    <script type="text/javascript">

    </script>
}

project.SistemaNF/CSharks.NFEs.WebApp/Views/Nfe/Index.cshtml
@using CSharks.NFEs.Domain.Models;
@{
    ViewData["Title"] = "Shark NFE - NFEs";
    List<EmitedNF> emiteds = ViewBag.ListEmiteds; 
}

<section>
    <div id="partial" class="mt-3">
        @await Html.PartialAsync("_MessageResult")
    </div>
     <h3> Notas emitidas </h3>
    <table id="dt-nf" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Data Emissão</th>
                <th>Serviço</th>
                <th>Número NFSE</th>
                <th>Cliente</th>
                <th>Valor</th>
                <th>Situação</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @if(emiteds != null && emiteds.Any())
            {
                foreach (EmitedNF emited in emiteds)
                {
                    <tr>
                        <td>@emited.EmitDate</td>
                        <td> @emited.ServiceName</td>
                        <td>@emited.NoNfse</td>
                        <td> @emited.ClientName</td>
                        <td>R$ @emited.ValueNF ,00</td>
                        @if (emited.Situation.Equals("Cancel"))
                        {
                            <td class="text-color-red"> <b> Cancelado </b></td>
                        }
                        else
                        {
                            <td class="text-color-green"> <b> Emitido </b></td>
                        }

                        <td>
                            <a class="btn btn-green" href="@emited.LinkPDF" target="_blank"><img class="img-btn" src="~/images/viewIcon-02-02-02.svg"></a>
                            <a class="btn btn-standard-1" onclick="downloadXML('@emited.EmitDate')"><img class="img-btn" src="~/images/downloadIcon-02-02.svg"></a>
                            <a class="btn btn-danger-1" onclick="cancelNF('@emited.NoNfse')"><img class="img-btn" src="~/images/cancelIcon-02-02-02.svg"></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</section>

@section Scripts {
    <script type="text/javascript">
        var showOptionsLink = document.getElementById("show-options");
        var optionsList = document.getElementById("options-list");
        showOptionsLink.addEventListener("click", function () {
            optionsList.style.display = "block";
        });

        function downloadXML(fname){
            $.ajax({
                url: '@Url.Action("DownloadAction", "Nfe")',
                data: {fileName : fname},
                type: "POST",
                dataType: "json",
                success: function (response) {
                    var downloadUrl = response.fileUrl;
                    var anchor = document.createElement('a');
                    anchor.href = downloadUrl;
                    anchor.download = 'NF.xml';
                    anchor.click();
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        }

        function cancelNF(noNfse){
            $.ajax({
                url: '@Url.Action("CancelNF", "CancelNF")',
                data: {noNfse : noNfse},
                type: "POST",
                success: function (response) {
                },
                error: function (xhr, status, error) {
                   alert("Já cancelada");
                }
            });
        };


    </script>
}

project.SistemaNF/CSharks.NFEs.WebApp/Views/Nfe/ListNF.cshtml
@{
    ViewData["Title"] = "Shark NFE - NFEs";
}

<section>
    <a class="btn btn-primary" asp-action="EmitNFE" asp-controller="Nfe"> Emitir </a>
</section>

@section Scripts {
    <script type="text/javascript">
        
    </script>
}